from motor_controller import MotorDriver
from time import sleep

if __name__ == "__main__":
    robot = MotorDriver()
    robot.set_speed(0.1, 0.1)
    print("0.1")
    sleep(3)
    robot.set_speed(0.2, 0.2)
    print("0.2")
    sleep(3)
    robot.set_speed(0.3, 0.3)
    print("0.3")
    sleep(3)
    robot.set_speed(0.4, 0.4)
    print("0.4")
    sleep(3)
    robot.set_speed(0.5, 0.5)
    print("0.5")
    sleep(3)
    robot.set_speed(0.6, 0.6)
    print("0.6")
    sleep(3)
    robot.set_speed(0.7, 0.7)
    print("0.7")
    sleep(3)
    robot.set_speed(0.8, 0.8)
    print("0.8")
    sleep(3)
    robot.set_speed(0.9, 0.9)
    print("0.9")
    sleep(3)
    robot.set_speed(1, 1)
    print("1")
    sleep(3)
