name: ROS

on:
  pull_request:
  push:
  workflow_dispatch:
    
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Test
        uses: ./.github/actions/test/

# https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html
  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Run linter
        uses: ./.github/actions/lint/
        env: 
          LINTER: ${{ matrix.linter }}