name: ROS

on:
  push:
    paths:
      - "src/**"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
  workflow_dispatch:
    
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        uses: ./.github/actions/test/

  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
          linter: [xmllint, flake8, pep257]
          #linter: [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Run linter
        uses: ./.github/actions/lint/
        env: 
          LINTER: ${{ matrix.linter }}
